# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 494ab77246eb3a19902b834f245cb8a9c5d66bb8eb7ca935ebfd8bae67ba53a4b0d8fb4e1dd0bd607acb74e0c44cd0d7e1054ea0d4733b46c462ddf63bacc3d7

test:
  secret_key_base: 66dd50ac5105d0fa910058b3e1b2e776bdc55bb62a976349bc1f797a2aa39d39b8f582e3240ba1c4e85e988277ce85174fe79da81c5317f517d67931097579fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
